export const REQUEST_VERCODE = 'REQUEST_VERCODE'
export const GET_VERCODE_SUCCESS = 'GET_VERCODE_SUCCESS'
export const GET_VERCODE_FAILURE = 'GET_VERCODE_FAILURE'

export const REQUEST_CHECK_VERCODE = 'REQUEST_CHECK_VERCODE'
export const CHECK_VERCODE_SUCCESS = 'CHECK_VERCODE_SUCCESS'
export const CHECK_VERCODE_FAILURE = 'CHECK_VERCODE_FAILURE'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const GET_MEMBER_INFO_SUCCESS = 'GET_MEMBER_INFO_SUCCESS'
export const GET_MEMBER_INFO_FAILURE = 'GET_MEMBER_INFO_FAILURE'

export const GET_LOGIN_STATUS_SUCCESS = 'GET_LOGIN_STATUS_SUCCESS'
export const GET_LOGIN_STATUS_FAILURE = 'GET_LOGIN_STATUS_FAILURE'
