export const REQUEST_CREATE_ORDER = 'REQUEST_CREATE_ORDER'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const GET_CONFIRM_CODE_SUCCESS = 'GET_CONFIRM_CODE_SUCCESS'
export const GET_CONFIRM_CODE_FAILURE = 'GET_CONFIRM_CODE_FAILURE'
