export const GET_TECOMMITEM_PROPERTY_SUCCESS = 'GET_TECOMMITEM_PROPERTY_SUCCESS'
export const GET_TECOMMITEM_PROPERTY_FAILURE = 'GET_TECOMMITEM_PROPERTY_FAILURE'

export const CALCULATOR_PRICE_SUCCESS = 'CALCULATOR_PRICE_SUCCESS'
export const CALCULATOR_PRICE_FAILURE = 'CALCULATOR_PRICE_FAILURE'

export const SAVE_CALCULATOR_PARAMS = 'SAVE_CALCULATOR_PARAMS'

export const INIT_CALCULATOR_PRICE = 'INIT_CALCULATOR_PRICE'
