export const GET_BANK_SUCCESS = 'GET_BANK_SUCCESS'
export const GET_BANK_FAILURE = 'GET_BANK_FAILURE'

export const CREATE_MEMBER_ACCOUNT_SUCCESS = 'CREATE_MEMBER_ACCOUNT_SUCCESS'
export const CREATE_MEMBER_ACCOUNT_FAILURE = 'CREATE_MEMBER_ACCOUNT_FAILURE'

export const GET_LAST_MEMBER_ACCOUNT_SUCCESS = 'GET_LAST_MEMBER_ACCOUNT_SUCCESS'
export const GET_LAST_MEMBER_ACCOUNT_FAILURE = 'GET_LAST_MEMBER_ACCOUNT_FAILURE'

export const REQUEST_EXPENDITURE = 'REQUEST_EXPENDITURE'
export const EXPENDITURE_SUCCESS = 'EXPENDITURE_SUCCESS'
export const EXPENDITURE_FAILURE = 'EXPENDITURE_FAILURE'

