export const GET_MEMBER_ACCOUNT_SUCCESS = 'GET_MEMBER_ACCOUNT_SUCCESS'
export const GET_MEMBER_ACCOUNT_FAILURE = 'GET_MEMBER_ACCOUNT_FAILURE'

export const GET_ACCOUNT_DETAIL_SUCCESS = 'GET_ACCOUNT_DETAIL_SUCCESS'
export const GET_ACCOUNT_DETAIL_FAILURE = 'GET_ACCOUNT_DETAIL_FAILURE'
