export const GET_TECOMMITEM_SUCCESS = 'GET_TECOMMITEM_SUCCESS'
export const GET_TECOMMITEM_FAILURE = 'GET_TECOMMITEM_FAILURE'

// export const GET_LOGIN_STATUS_SUCCESS = 'GET_LOGIN_STATUS_SUCCESS'
// export const GET_LOGIN_STATUS_FAILURE = 'GET_LOGIN_STATUS_FAILURE'

export const GET_VERCODE_SUCCESS = 'GET_VERCODE_SUCCESS'
export const GET_VERCODE_FAILURE = 'GET_VERCODE_FAILURE'
